#arquivo docker-compose para subir ambiente
#wordpress - mariadb - phpmyadmin
#19/08/2021 André R Mendes
#testado e funcionando.

version: '3.1'

services: 

  wordpressdb:                                        #nome para container DB
    image: mariadb
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wordpress
    networks:                                          #rede que foi criada p/ ambiente
     - wpnet
    volumes: 
      - /root/wordpress/database:/var/lib/mysql       


  wordpress:                                          #container com o wordpress
    depends_on:
     - wordpressdb
    image: wordpress
    restart: always
    #links:                                           #antigo, trocado por networks
    # - wordpressdb:mysql
    environment: 
        WORDPRESS_DB_HOST: wordpressdb:3306
        WORDPRESS_DB_USER: root 
        WORDPRESS_DB_PASSWORD: 1234
    networks: 
     - wpnet
    ports: 
     - "80:80"
    volumes: 
     - /root/wordpress/html:/var/www/html
  
  myadmin:                                          #container phpmyadmin
    depends_on: 
     - wordpressdb
    image: phpmyadmin
    restart: always
    #links: 
    # - wordpressdb:mysql
    environment: 
      PMA_HOST: wordpressdb
      WORDPRESS_DB_PASSWORD: 1234
    networks: 
     - wpnet
    ports: 
     - "8000:80"

networks: 
 wpnet:

